name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    # will build for linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azolfagharj/action-caddy-builder@v1.0.7
        id: build
        with:
          caddy-version: latest
          modules: |
            github.com/caddy-dns/porkbun
            github.com/caddyserver/forwardproxy
      - uses: actions/upload-artifact@v4
        with:
          name: caddy-binary
          path: ${{ steps.build.outputs.caddy-path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - uses: softprops/action-gh-release@v2
        with:
          files: caddy-binary/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}